const STORAGE_KEY = "nossa-casa-invoices-v1";

const form = document.getElementById("invoice-form");
const invoiceIdInput = document.getElementById("invoice-id");
const descriptionInput = document.getElementById("description");
const categoryInput = document.getElementById("category");
const amountInput = document.getElementById("amount");
const dueDateInput = document.getElementById("due-date");
const paymentStatusInput = document.getElementById("payment-status");
const scheduledDateInput = document.getElementById("scheduled-date");
const paidDateInput = document.getElementById("paid-date");
const barcodeInput = document.getElementById("barcode");
const isRecurringInput = document.getElementById("is-recurring");

const scheduledDateWrap = document.getElementById("scheduled-date-wrap");
const paidDateWrap = document.getElementById("paid-date-wrap");

const cancelEditButton = document.getElementById("cancel-edit");
const clearAllButton = document.getElementById("clear-all");
const exportJsonButton = document.getElementById("export-json");
const importJsonInput = document.getElementById("import-json");
const importCsvInput = document.getElementById("import-csv");

const filterMonthInput = document.getElementById("filter-month");
const filterCategoryInput = document.getElementById("filter-category");
const filterStatusInput = document.getElementById("filter-status");

const summaryCards = document.getElementById("summary-cards");
const tableBody = document.getElementById("invoice-table-body");

let invoices = loadInvoices();
let monthlyChart;
let categoryChart;

initialize();

function initialize() {
  filterMonthInput.value = currentYearMonth();
  ensureRecurringInvoicesGenerated();
  updateStatusFieldsVisibility();
  bindEvents();
  renderAll();
}

function bindEvents() {
  form.addEventListener("submit", onFormSubmit);
  paymentStatusInput.addEventListener("change", updateStatusFieldsVisibility);
  cancelEditButton.addEventListener("click", resetForm);

  filterMonthInput.addEventListener("change", renderAll);
  filterCategoryInput.addEventListener("change", renderAll);
  filterStatusInput.addEventListener("change", renderAll);

  clearAllButton.addEventListener("click", onClearAll);
  exportJsonButton.addEventListener("click", exportJson);
  importJsonInput.addEventListener("change", importJson);
  importCsvInput.addEventListener("change", importCsv);
}

function onFormSubmit(event) {
  event.preventDefault();

  const entry = {
    id: invoiceIdInput.value || crypto.randomUUID(),
    description: descriptionInput.value.trim(),
    category: categoryInput.value,
    amount: Number(amountInput.value),
    dueDate: dueDateInput.value,
    paymentStatus: paymentStatusInput.value,
    scheduledDate: scheduledDateInput.value || "",
    paidDate: paidDateInput.value || "",
    barcode: barcodeInput.value.trim(),
    isRecurring: isRecurringInput.checked,
    recurrenceGroupId: "",
    autogenerated: false,
    createdAt: new Date().toISOString()
  };

  if (!entry.description || !entry.category || !entry.dueDate || Number.isNaN(entry.amount)) {
    alert("Preencha os campos obrigatorios corretamente.");
    return;
  }

  if (entry.paymentStatus === "scheduled" && !entry.scheduledDate) {
    alert("Informe a data programada para pagamento.");
    return;
  }

  if (entry.paymentStatus === "paid" && !entry.paidDate) {
    entry.paidDate = entry.dueDate;
  }

  if (entry.paymentStatus !== "scheduled") {
    entry.scheduledDate = "";
  }

  if (entry.paymentStatus !== "paid") {
    entry.paidDate = "";
  }

  const existingIndex = invoices.findIndex((invoice) => invoice.id === entry.id);
  if (existingIndex >= 0) {
    const existing = invoices[existingIndex];
    entry.recurrenceGroupId = existing.recurrenceGroupId || "";
    entry.autogenerated = existing.autogenerated || false;
    entry.createdAt = existing.createdAt || entry.createdAt;
    invoices[existingIndex] = entry;
  } else {
    if (entry.isRecurring) {
      entry.recurrenceGroupId = crypto.randomUUID();
    }
    invoices.push(entry);
  }

  saveInvoices();
  ensureRecurringInvoicesGenerated();
  renderAll();
  resetForm();
}

function updateStatusFieldsVisibility() {
  const status = paymentStatusInput.value;
  scheduledDateWrap.style.display = status === "scheduled" ? "grid" : "none";
  paidDateWrap.style.display = status === "paid" ? "grid" : "none";
}

function resetForm() {
  form.reset();
  invoiceIdInput.value = "";
  paymentStatusInput.value = "open";
  updateStatusFieldsVisibility();
}

function onClearAll() {
  const confirmed = confirm("Deseja realmente apagar todas as faturas cadastradas?");
  if (!confirmed) {
    return;
  }

  invoices = [];
  saveInvoices();
  renderAll();
}

function getFilteredInvoices() {
  const month = filterMonthInput.value;
  const category = filterCategoryInput.value;
  const status = filterStatusInput.value;

  return invoices
    .filter((invoice) => {
      if (month && invoice.dueDate.slice(0, 7) !== month) {
        return false;
      }
      if (category !== "all" && invoice.category !== category) {
        return false;
      }
      if (status !== "all" && invoice.paymentStatus !== status) {
        return false;
      }
      return true;
    })
    .sort((a, b) => a.dueDate.localeCompare(b.dueDate));
}

function renderAll() {
  const filtered = getFilteredInvoices();
  renderTable(filtered);
  renderSummaryCards(filtered);
  renderCharts();
}

function renderTable(filtered) {
  tableBody.innerHTML = "";

  if (!filtered.length) {
    tableBody.innerHTML = `<tr><td colspan="8">Nenhuma fatura encontrada para os filtros selecionados.</td></tr>`;
    return;
  }

  filtered.forEach((invoice) => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${escapeHtml(invoice.description)}${invoice.autogenerated ? " <small>(auto)</small>" : ""}</td>
      <td>${escapeHtml(invoice.category)}</td>
      <td>${formatCurrency(invoice.amount)}</td>
      <td>${formatDate(invoice.dueDate)}</td>
      <td><span class="badge ${invoice.paymentStatus}">${statusLabel(invoice.paymentStatus)}</span></td>
      <td>${invoice.scheduledDate ? formatDate(invoice.scheduledDate) : "-"}</td>
      <td>${renderBarcodeCell(invoice)}</td>
      <td class="actions">
        <button class="btn btn-muted" type="button" data-action="edit" data-id="${invoice.id}">Editar</button>
        <button class="btn btn-danger" type="button" data-action="delete" data-id="${invoice.id}">Excluir</button>
      </td>
    `;
    tableBody.appendChild(tr);
  });

  tableBody.querySelectorAll("button[data-action='edit']").forEach((button) => {
    button.addEventListener("click", () => onEdit(button.dataset.id));
  });

  tableBody.querySelectorAll("button[data-action='delete']").forEach((button) => {
    button.addEventListener("click", () => onDelete(button.dataset.id));
  });

  tableBody.querySelectorAll("button[data-action='copy-barcode']").forEach((button) => {
    button.addEventListener("click", async () => {
      const value = button.dataset.value;
      try {
        await navigator.clipboard.writeText(value);
        alert("Codigo de barras copiado.");
      } catch {
        alert("Nao foi possivel copiar. Copie manualmente.");
      }
    });
  });
}

function renderBarcodeCell(invoice) {
  if (!invoice.barcode) {
    return "-";
  }

  const compact = escapeHtml(invoice.barcode);
  return `<span title="${compact}">${compact.slice(0, 18)}${compact.length > 18 ? "..." : ""}</span> <button class="btn btn-muted" type="button" data-action="copy-barcode" data-value="${compact}">Copiar</button>`;
}

function onEdit(id) {
  const invoice = invoices.find((item) => item.id === id);
  if (!invoice) {
    return;
  }

  invoiceIdInput.value = invoice.id;
  descriptionInput.value = invoice.description;
  categoryInput.value = invoice.category;
  amountInput.value = invoice.amount;
  dueDateInput.value = invoice.dueDate;
  paymentStatusInput.value = invoice.paymentStatus;
  scheduledDateInput.value = invoice.scheduledDate;
  paidDateInput.value = invoice.paidDate;
  barcodeInput.value = invoice.barcode;
  isRecurringInput.checked = Boolean(invoice.isRecurring);

  updateStatusFieldsVisibility();
}

function onDelete(id) {
  const invoice = invoices.find((item) => item.id === id);
  if (!invoice) {
    return;
  }

  const confirmed = confirm(`Excluir fatura ${invoice.description}?`);
  if (!confirmed) {
    return;
  }

  invoices = invoices.filter((item) => item.id !== id);
  saveInvoices();
  renderAll();
}

function renderSummaryCards(filtered) {
  const total = sum(filtered.map((item) => item.amount));
  const paid = sum(filtered.filter((item) => item.paymentStatus === "paid").map((item) => item.amount));
  const scheduled = sum(filtered.filter((item) => item.paymentStatus === "scheduled").map((item) => item.amount));
  const open = sum(filtered.filter((item) => item.paymentStatus === "open").map((item) => item.amount));
  const overdue = sum(
    filtered
      .filter((item) => item.paymentStatus !== "paid" && item.dueDate < todayString())
      .map((item) => item.amount)
  );

  const cards = [
    ["Total no mes", formatCurrency(total)],
    ["Pago", formatCurrency(paid)],
    ["Programado", formatCurrency(scheduled)],
    ["Em aberto", formatCurrency(open)],
    ["Em atraso", formatCurrency(overdue)]
  ];

  summaryCards.innerHTML = cards
    .map(
      ([title, value]) => `
      <article class="card">
        <h4>${title}</h4>
        <p>${value}</p>
      </article>
    `
    )
    .join("");
}

function renderCharts() {
  const monthlyCanvas = document.getElementById("monthly-chart");
  const categoryCanvas = document.getElementById("category-chart");

  const monthlyData = getMonthlyComparison();
  const categoryData = getCurrentMonthCategoryBreakdown();

  if (monthlyChart) {
    monthlyChart.destroy();
  }

  monthlyChart = new Chart(monthlyCanvas, {
    type: "line",
    data: {
      labels: monthlyData.labels,
      datasets: [
        {
          label: "Total de despesas",
          data: monthlyData.values,
          borderColor: "#c4673f",
          backgroundColor: "rgba(196, 103, 63, 0.25)",
          borderWidth: 3,
          tension: 0.28,
          fill: true,
          pointRadius: 4
        }
      ]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          ticks: {
            callback(value) {
              return `R$ ${Number(value).toLocaleString("pt-BR")}`;
            }
          }
        }
      },
      plugins: {
        legend: {
          display: false
        }
      }
    }
  });

  if (categoryChart) {
    categoryChart.destroy();
  }

  categoryChart = new Chart(categoryCanvas, {
    type: "doughnut",
    data: {
      labels: categoryData.labels,
      datasets: [
        {
          data: categoryData.values,
          backgroundColor: [
            "#c4673f",
            "#3f7a67",
            "#d18f2f",
            "#779b3f",
            "#7c6db9",
            "#5a8ccf",
            "#b35f87",
            "#e1b63f",
            "#8f7d6f"
          ]
        }
      ]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: "bottom"
        }
      }
    }
  });
}

function getMonthlyComparison() {
  const labels = [];
  const values = [];

  const current = new Date(`${currentYearMonth()}-01T00:00:00`);
  for (let i = 5; i >= 0; i -= 1) {
    const date = new Date(current.getFullYear(), current.getMonth() - i, 1);
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
    labels.push(`${String(date.getMonth() + 1).padStart(2, "0")}/${date.getFullYear()}`);

    const total = sum(invoices.filter((item) => item.dueDate.slice(0, 7) === key).map((item) => item.amount));
    values.push(Number(total.toFixed(2)));
  }

  return { labels, values };
}

function getCurrentMonthCategoryBreakdown() {
  const month = filterMonthInput.value || currentYearMonth();
  const inMonth = invoices.filter((item) => item.dueDate.slice(0, 7) === month);

  const byCategory = new Map();
  inMonth.forEach((item) => {
    byCategory.set(item.category, (byCategory.get(item.category) || 0) + item.amount);
  });

  const labels = Array.from(byCategory.keys());
  const values = labels.map((label) => Number(byCategory.get(label).toFixed(2)));

  return {
    labels: labels.length ? labels : ["Sem dados"],
    values: values.length ? values : [1]
  };
}

function ensureRecurringInvoicesGenerated() {
  const recurringSources = invoices.filter((item) => item.isRecurring);
  let changed = false;

  recurringSources.forEach((item) => {
    if (!item.recurrenceGroupId) {
      item.recurrenceGroupId = crypto.randomUUID();
      changed = true;
    }

    const sourceDate = new Date(`${item.dueDate}T00:00:00`);

    for (let offset = 1; offset <= 2; offset += 1) {
      const generatedDate = new Date(sourceDate.getFullYear(), sourceDate.getMonth() + offset, sourceDate.getDate());
      const dueDate = formatDateIso(generatedDate);
      const monthKey = dueDate.slice(0, 7);

      const exists = invoices.some(
        (invoice) =>
          invoice.recurrenceGroupId === item.recurrenceGroupId &&
          invoice.dueDate.slice(0, 7) === monthKey
      );

      if (!exists) {
        invoices.push({
          id: crypto.randomUUID(),
          description: item.description,
          category: item.category,
          amount: item.amount,
          dueDate,
          paymentStatus: "open",
          scheduledDate: "",
          paidDate: "",
          barcode: item.barcode,
          isRecurring: true,
          recurrenceGroupId: item.recurrenceGroupId,
          autogenerated: true,
          createdAt: new Date().toISOString()
        });
        changed = true;
      }
    }
  });

  if (changed) {
    saveInvoices();
  }
}

function exportJson() {
  const payload = JSON.stringify(invoices, null, 2);
  const blob = new Blob([payload], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `despesas-nossa-casa-${currentYearMonth()}.json`;
  link.click();
  URL.revokeObjectURL(url);
}

function importJson(event) {
  const file = event.target.files?.[0];
  if (!file) {
    return;
  }

  const reader = new FileReader();
  reader.onload = () => {
    try {
      const parsed = JSON.parse(String(reader.result));
      if (!Array.isArray(parsed)) {
        throw new Error("Arquivo invalido");
      }

      const normalized = parsed
        .map((item) => normalizeImportedInvoice(item))
        .filter(Boolean);

      invoices = mergeById(invoices, normalized);
      saveInvoices();
      ensureRecurringInvoicesGenerated();
      renderAll();
      alert("Importacao de JSON concluida.");
    } catch {
      alert("Nao foi possivel importar o JSON.");
    } finally {
      event.target.value = "";
    }
  };
  reader.readAsText(file);
}

function importCsv(event) {
  const file = event.target.files?.[0];
  if (!file) {
    return;
  }

  const reader = new FileReader();
  reader.onload = () => {
    try {
      const text = String(reader.result || "");
      const imported = parseCsv(text).map((item) => normalizeImportedInvoice(item)).filter(Boolean);
      invoices = mergeById(invoices, imported);
      saveInvoices();
      ensureRecurringInvoicesGenerated();
      renderAll();
      alert("Importacao de CSV concluida.");
    } catch {
      alert("Nao foi possivel importar o CSV.");
    } finally {
      event.target.value = "";
    }
  };
  reader.readAsText(file);
}

function parseCsv(text) {
  const rows = text.split(/\r?\n/).filter((line) => line.trim());
  if (rows.length < 2) {
    return [];
  }

  const headers = rows[0].split(",").map((part) => part.trim().toLowerCase());

  return rows.slice(1).map((row) => {
    const values = row.split(",").map((part) => part.trim());
    const obj = {};
    headers.forEach((header, index) => {
      obj[header] = values[index] || "";
    });

    return {
      description: obj.description || obj.descricao || obj.servico || obj.servico_produto || "",
      category: obj.category || obj.categoria || "Outros",
      amount: obj.amount || obj.valor || "0",
      dueDate: obj.duedate || obj.vencimento || "",
      paymentStatus: obj.paymentstatus || obj.status || "open",
      scheduledDate: obj.scheduleddate || obj.dataprogramada || "",
      paidDate: obj.paiddate || obj.datapagamento || "",
      barcode: obj.barcode || obj.codigodebarras || "",
      isRecurring: ["true", "1", "sim", "yes"].includes(String(obj.isrecurring || obj.recorrente).toLowerCase())
    };
  });
}

function normalizeImportedInvoice(data) {
  if (!data) {
    return null;
  }

  const amount = Number(String(data.amount || 0).replace(".", "").replace(",", "."));
  const dueDate = normalizeDate(data.dueDate);

  if (!data.description || !dueDate || Number.isNaN(amount)) {
    return null;
  }

  const status = ["open", "scheduled", "paid"].includes(data.paymentStatus) ? data.paymentStatus : "open";

  return {
    id: data.id || crypto.randomUUID(),
    description: String(data.description).trim(),
    category: data.category || "Outros",
    amount,
    dueDate,
    paymentStatus: status,
    scheduledDate: normalizeDate(data.scheduledDate),
    paidDate: normalizeDate(data.paidDate),
    barcode: data.barcode ? String(data.barcode).trim() : "",
    isRecurring: Boolean(data.isRecurring),
    recurrenceGroupId: data.recurrenceGroupId || "",
    autogenerated: Boolean(data.autogenerated),
    createdAt: data.createdAt || new Date().toISOString()
  };
}

function normalizeDate(value) {
  if (!value) {
    return "";
  }

  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }

  if (/^\d{2}\/\d{2}\/\d{4}$/.test(value)) {
    const [day, month, year] = value.split("/");
    return `${year}-${month}-${day}`;
  }

  return "";
}

function mergeById(current, incoming) {
  const map = new Map();
  [...current, ...incoming].forEach((item) => {
    map.set(item.id, item);
  });
  return Array.from(map.values());
}

function loadInvoices() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      return [];
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveInvoices() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(invoices));
}

function statusLabel(status) {
  return {
    open: "Em aberto",
    scheduled: "Programado",
    paid: "Pago"
  }[status] || "Em aberto";
}

function formatDateIso(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function todayString() {
  return formatDateIso(new Date());
}

function currentYearMonth() {
  return todayString().slice(0, 7);
}

function formatDate(isoDate) {
  if (!isoDate) {
    return "-";
  }

  const [year, month, day] = isoDate.split("-");
  return `${day}/${month}/${year}`;
}

function formatCurrency(value) {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);
}

function sum(values) {
  return values.reduce((acc, value) => acc + Number(value || 0), 0);
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
